### ISSUE TITLE
Consistent timeunit use across framework

### ISSUE THREAD

**Issue by jessicamarshall** [Orasi/Chameleon#117]
Background: Sleeper statement takes milliseconds while all other syncs/timeouts take seconds.  This has caused confusion in projects where clients will use seconds in sleeper statements and milliseconds in syncs causing unpredictable results - excessively long syncs or super short hard waits.

Consider having chameleon only use milliseconds across whole framework.  Would need to update all the syncs and also the default timeouts in constants class.  Webdriver takes timeunit for implicit waits, so will need to update that to milliseconds.

**Comment by jessicamarshall** [comment]
Update this class to use seconds instead:
https://github.com/Orasi/Chameleon/blob/master/src/main/java/com/orasi/utils/Sleeper.java

Can we consider having a runtime exception thrown if the value is greater than 600?  You can make this a constant in the constant class.

Also will need to check any references to sleep to change from milliseconds to seconds.  Should only be in PageLoaded class.

**Comment by zach-apple** [comment]
Implemented in #156
