### ISSUE TITLE
Emailable report - sortable columns

### ISSUE THREAD

**Issue by jessicamarshall** [Orasi/Chameleon#121]
Add sortable columns to the emailable report

**Comment by JustinPhlegar** [comment]
While we are looking at this, can timezone prefix also be added to the time print out. Being emailed, there is no telling what timezone people will be in when they receive it.

![image](https://user-images.githubusercontent.com/8030679/30974575-f8208afa-a43d-11e7-8529-7fdc15a6107e.png)
