### ISSUE TITLE
Rename the 'Selenium-Java-Core' to 'Java-Opensource-Toolkit'

### ISSUE THREAD

**Issue by adamdthomas** [Orasi/Chameleon#54]

**Comment by jessicamarshall** [comment]
These are the steps to follow:
GitHub:
1. Rename the repository on GitHub - Java-Opensource-Toolkit
Local Machine:
1. Rename the folder where you're repository is stored locally 
2. Open the .project file and edit the xml node of <name> to the new name
3. Go to the hidden folder .git, edit the config file and change the remote origin url to the newly renamed repo URL from github.
4. Push up your changes

You will probably have to remove the project from eclipse, and then do a re-import to see changes in eclipse.

**Comment by JustinPhlegar** [comment]
Completed a while back ago. Closing
