### ISSUE TITLE
getWrappedDriver() method in LinkImpl class causes infinite loop

### ISSUE THREAD

**Issue by jessicamarshall** [Orasi/Chameleon#72]
In the stage branch, the below method causes an infinite loop when using the Link class.  I commented it out of the xeeva project, but not sure what it's intentions are, or if it needs to be somewhere else.

Line 60
    @Override
    public OrasiDriver getWrappedDriver() {
        if (driver == null)
            return getWrappedDriver();
        return driver;
    }

**Comment by JustinPhlegar** [comment]
What class was it in? I cannot not find that code in [LinkImpl](https://github.com/Orasi/Selenium-Java-Core/blob/stage/src/main/java/com/orasi/core/interfaces/impl/LinkImpl.java)

**Comment by JustinPhlegar** [comment]
Is already resolved in Stage branch, will close when Stage moves to Master
